#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Wed Nov 29 16:11:03 2017

@author: gracer
"""
import os
from multiprocessing import Pool

def run_level1():
    os.system("feat %s"%PATH2FEAT)


    
def main():
    basedir='/Users/gracer/Desktop/data/derivatives/task'

main()